### ISSUE TITLE
Enchantments can be acquired where they shouldn't be 

### ISSUE THREAD

**Issue by Bluberry-Kat** [SammySemicolon/ToolSharpening#1]
Using Forge 36.1.32, Tool Sharpening 1.16.5-1.0  
Both the Sharpened and Sharpness enchantments can currently be bought from librarian villagers.  
I reproduced this in a modpack with just Tool Sharpening, by placing a villager and repeatedly breaking and placing a lectern in-front of them until they produced the trade in question.

**Comment by cntrik** [comment]
[Suggestion to Issue for Mod Author] Instead of preventing acquiring Sharpness have it take on a different role, for an example the more kills you get the more damage it outputs. Anyways this mod is very interesting.

**Comment by SammySemicolon** [comment]
I wish there was an easier way for me to figure out that a github issue was posted instead of just randomly finding a notification in my email qwq. 
In my own testing I have been able to confirm that villagers can't sell sharpness, that's rlly bizarre. 
Gonna look into it sometime I guess

**Comment by Uraneptus** [comment]
This should be fixed in the 1.19.2 Port [Link](https://www.curseforge.com/minecraft/mc-mods/tool-sharpening/files/4477756)
